events: 3
g4_post_eta:
- -4.0
- 4.0
g4_post_pt: 300
g4_pre_eta:
- -3.0
- 3.0
g4_pre_pt: 150
g4_record_neutrals: true
g4_record_secondaries: false
geant4: true
hard_process: Top:qqbar2ttbar
output: outputs/itk_comparison/odd_output_config_pt150_eta-3.0_3.0_neutralsTrue_secondariesFalse
output_csv: false
pileup: 200
pythia: true
reco: false
