events: 3
g4_post_eta:
- -4.0
- 4.0
g4_post_pt: 300
g4_pre_eta:
- -3.0
- 3.0
g4_pre_pt: 100
g4_record_neutrals: false
g4_record_secondaries: true
geant4: true
hard_process: Top:qqbar2ttbar
output: outputs/itk_comparison/odd_output_config_pt100_eta-3.0_3.0_neutralsFalse_secondariesTrue
output_csv: false
pileup: 200
pythia: true
reco: false
