_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 9
                - 55
                - 103
            "2":
                - 1
                - 9
                - 55
                - 103
            "3":
                - 2
                - 5
                - 14
                - 23
                - 55
                - 62
            "4": 3.11.11
            "5": 0.18.7
            "8":
                - 2
                - 5
            "12": 0.18.7
            "13": linux-x86_64
batch_size:
    value: 256
d_ff:
    value: 512
d_model:
    value: 128
dropout:
    value: 0.1
epochs:
    value: 50
grad_clip:
    value: 1
loss:
    value: huber
lr:
    value: 0.001
max_files:
    value: 50
max_hits:
    value: 20
max_train_samples:
    value: null
n_heads:
    value: 8
n_layers:
    value: 6
num_workers:
    value: 4
output_dir:
    value: /global/cfs/cdirs/m4958/data/ColliderML/ml/beamspot_studies/baseline_shifted_25um
overfit_batches:
    value: 0
parquet_base:
    value: /global/cfs/cdirs/m4958/data/ColliderML/simulation/beamspot_studies/ttbar_shifted_25um/v1/parquet
patience:
    value: 10
seed:
    value: 42
val_split:
    value: 0.1
wandb_name:
    value: baseline-shifted-25um
wandb_project:
    value: colliderml-beamspot
weight_decay:
    value: 1e-05
