output: "outputs/pda_tests/pda_testing_susy1"
events: 1
pythia: true
geant4: true
hard_process: "SUSY:qqbar2chi0chi0"
pileup: 0
output_csv: false
reco: false

# Geant4 config
g4_pre_pt: 100.0
g4_pre_eta: [-4.0, 4.0]
g4_post_pt: 1
g4_post_eta: [-4.0, 4.0]
g4_record_neutrals: true
g4_record_secondaries: true
