# Example configuration
campaign: "full_pileup"
dataset: "diphoton"
version: "v1"
stage: "pythia_generation"  # One of: generation, merge_smear, simulation, digitization
job_config:
  # Number of nodes will be calculated as n_runs / runs_per_node
  n_runs: 2100  # Number of runs (where a run produces N events)
  runs_per_node: 16  # Number of runs per node
  time_limit: "00:30:00"  # Time limit per job
  qos: "regular"
  execution_mode: "multi_node_slurm"

# Stage-specific configurations
events: 64  # Number of events per run, total number of events will be n_runs * events
pileup: 200
hard_process:
vertex_sigma_xy: 0.0125 # mm
vertex_sigma_z: 55.5 # mm
vertex_sigma_t: 0.185 # ns

merge: true  # Merge with existing signal file (events.hepmc3 or events.hepmc.gz) in output directory

poisson_sample: true
poisson_buffer_sigma: 5.0 # Used to generate the buffer for the Poisson sampling