#========================================================================
# YAML Configuration for Digitization of ttbar Events
#========================================================================

# --- Dataset & Version ---
campaign: "full_pileup_mini_pilot"
dataset: "ttbar"
version: "v6"
stage: "digitization"  # One of: generation, merge_smear, simulation, digitization

# --- Job Configuration ---
job_config:
  execution_mode: "interactive"
  n_runs: 10  # Number of jobs to submit
  runs_per_node: 10  # Number of runs per node
  time_limit: "00:30:00"  # Time limit per job
  qos: "debug"

# --- Validation Configuration ---
validation_config:

# --- Stage-specific Configurations ---
events: 16  # Number of events per run, total number of events will be n_runs * events
threads: 16
digi: True
reco: True

# --- Writing Configuration ---
output_root: True
performance_metrics: True
output_csv: True
output_all_particles: False

# --- Digitization config ---
# digi_config: /global/cfs/cdirs/m4958/usr/danieltm/ColliderML/software/colliderml_dev/scripts/simulation/odd-full-geo-digi-config.json

# --- Debugging Commands ---
debug_output_dir: /pscratch/sd/d/danieltm/ColliderML/simulation/full_pileup_mini_pilot/ttbar/v6/runs/2