# Example configuration
campaign: "single_particle_pilot"
dataset: "single_pion"
version: "v3"
stage: "simulation"  # One of: generation, merge_smear, simulation, digitization
job_config:
  # Number of nodes will be calculated as n_runs / runs_per_node
  n_runs: 1  # Number of jobs to submit
  runs_per_node: 1  # Number of runs per node
  time_limit: "04:00:00"  # Time limit per job
  qos: "regular"
  execution_mode: "interactive"

validation_config:
  time_limit: "00:10:00"
  qos: "regular"

# Stage-specific configurations
events: 1000  # Number of events per run, total number of events will be n_runs * events
threads: 8
input_filename: events.hepmc3
minimalKineticEnergy: 0.1  # Minimum kinetic energy in GeV to register in truth
truthParticleHandler: "Geant4FullTruthParticleHandler"

debug_output_dir: "/global/cfs/cdirs/m4958/data/ColliderML/public/single_particle_pilot/single_pion/v3/runs/0"

