# Example configuration
campaign: "full_pileup_mini_pilot"
dataset: "zee"
version: "v2"
stage: "simulation"  # One of: generation, merge_smear, simulation, digitization
job_config:
  # Number of nodes will be calculated as n_runs / runs_per_node
  n_runs: 13  # Number of jobs to submit
  runs_per_node: 8  # Number of runs per node
  time_limit: "06:00:00"  # Time limit per job
  qos: "regular"
  depends_on: "42128591"
  execution_mode: "distributed_slurm"

validation_config:
  # time_limit: "00:10:00"
  # qos: "regular"

# Stage-specific configurations
events: 128  # Number of events per run, total number of events will be n_runs * events
threads: 8
minimalKineticEnergy: 0.001  # Minimum kinetic energy in GeV to register in truth
truthParticleHandler: "Geant4FullTruthParticleHandler"

