# Example configuration
campaign: "full_pileup_pilot"
dataset: "dihiggs"
version: "v4"
stage: "simulation"  # One of: generation, merge_smear, simulation, digitization
job_config:
  # Number of nodes will be calculated as n_runs / runs_per_node
  n_runs: 128  # Number of jobs to submit
  runs_per_node: 32  # Number of runs per node
  time_limit: "04:00:00"  # Time limit per job
  qos: "regular"
  execution_mode: "interactive"

validation_config:
  time_limit: "00:10:00"
  qos: "regular"

# Stage-specific configurations
events: 32  # Number of events per run, total number of events will be n_runs * events
threads: 8
minimalKineticEnergy: 0.001  # Minimum kinetic energy in GeV to register in truth
truthParticleHandler: "Geant4FullTruthParticleHandler"

