#========================================================================
# YAML Configuration for Digitization of ttbar Events
#========================================================================

# --- Dataset & Version ---
campaign: "hard_scatter"
dataset: "ttbar"
version: "v1"
stage: "digitization"  # One of: generation, merge_smear, simulation, digitization

# --- Job Configuration ---
job_config:
  # n_runs: 1024  # Number of jobs to submit
  n_runs: 16
  runs_per_node: 4  # Number of runs per node
  time_limit: "00:30:00"  # Time limit per job
  qos: "debug"
  execution_mode: "multi_node_slurm"
  # execution_mode: "interactive"
  depends_on:

# --- Validation Configuration ---
validation_config:
  enabled: True

# --- Stage-specific Configurations ---
events: 1280  # Number of events per run, total number of events will be n_runs * events
threads: 32
digi: True
reco: True
# spacepoints: True  # Write spacepoints to ROOT (requires digi: True)
num_seeds_per_spm: 40

# --- Writing Configuration ---
output_root: True
performance_metrics: True
output_csv: True
output_all_particles: True

# --- Digitization config ---
digi_config: /global/cfs/cdirs/m4958/usr/danieltm/ColliderML/software/colliderml_dev/scripts/simulation/odd-full-geo-digi-config.json

# --- Spacepoint config ---
# spacepoint_geometry_selection: /global/cfs/cdirs/m4958/usr/danieltm/ColliderML/software/OtherLibraries/acts_versions/acts_v4/Examples/Configs/odd-strip-spacepoint-selection.json

# --- Debugging Commands ---
# debug_output_dir: /global/cfs/cdirs/m4958/data/ColliderML/simulation/hard_scatter/ttbar/v1/runs/0