events: 1
g4_post_eta:
- -4.0
- 4.0
g4_post_pt: 0.1
g4_pre_eta:
- -4.0
- 4.0
g4_pre_pt: 100
g4_record_neutrals: false
g4_record_secondaries: true
geant4: true
hard_process: Top:qqbar2ttbar
output: outputs/itk_comparison/odd_output_config_pt100_postpt0.1_eta-4.0_4.0_neutralsFalse_secondariesTrue
output_csv: false
pileup: 200
pythia: true
reco: false
